### ISSUE TITLE
ModuleNotFoundError: No module named 'sentence_transformers.evaluation'

### ISSUE THREAD

**Issue by DavidBegert** [UKPLab/sentence-transformers#10]
After pip installing and trying to import SentenceTransformer I get this error: 
ModuleNotFoundError: No module named 'sentence_transformers.evaluation'

When I look into the source code the only folder I have is models. I am missing evaluation, etc.
Any Idea why?

**Comment by nreimers** [comment]
That is strange.

Maybe try to checkout the repository and install it from sources with
pip install .

Will check why there is no evaluation folder when installed with pip

**Comment by DavidBegert** [comment]
I cloned the repo and did pip install . but it was still missing. Did you want me to try checking out to a previous commit?

**Comment by nreimers** [comment]
Have you tried to install it with
pip install sentence-transformers

**Comment by nreimers** [comment]
I found the issue: The setup.py did not correctly specify the packages.

I released a new version to pypi (0.2.1) which can be installed via:
pip install -U sentence-transformers

Also, installing it from sources should work again.

It should work then. Thanks for reporting.

**Comment by rishabh547** [comment]
> pip install -U sentence-transformers

Hey Can you explain what does it mean to install from sources? I have tried everything from normal pip  to U- sentence transformer one but it still shows no module found named Sentence_transformer.

![image](https://user-images.githubusercontent.com/59617133/112956697-5a210980-915e-11eb-86f3-1a6aa56e3086.png)

See in the above pic , after installing it still shows  no module found!

Would really appreciate your help! & Please Replay ASAP

**Comment by rishabh547** [comment]
Would Really appreciate help from anyone! Thank you in Advance

**Comment by shivprasad94** [comment]
![image](https://user-images.githubusercontent.com/13836633/117250328-b0215500-ae60-11eb-9a88-2f7bd311f4dd.png)

Same issue here.
Would really appreciate your help!

**Comment by nreimers** [comment]
You have to run the following command:
```
from sentence_transformers import SentenceTransformer
```

**Comment by Salamit** [comment]
I'm having the same issue. 
<img width="613" alt="Screen Shot 2021-10-03 at 4 47 56 PM" src="https://user-images.githubusercontent.com/12544262/135744941-3d87f82e-ca8a-44f0-96ed-c38ac06f9330.png">
<img width="553" alt="Screen Shot 2021-10-03 at 4 48 29 PM" src="https://user-images.githubusercontent.com/12544262/135744962-7ec9f7f3-b7bc-4805-bb50-8d2109ebfa50.png">

**Comment by nreimers** [comment]
@Salamit 
You cannot name your file sentence-transformers.py

Also make sure you have it installed using pip or conda

**Comment by Salamit** [comment]
@nreimers Thanks! I used pip to install it. 
Also I changed the file name and I'm still getting the same error.
<img width="718" alt="Screen Shot 2021-10-03 at 4 59 42 PM" src="https://user-images.githubusercontent.com/12544262/135745263-acab9dfe-8c21-45eb-8742-6339da875053.png">

**Comment by yes-its-shivam** [comment]
i had the same error while using "from sentence_transformers import SentenceTransformer" code in jupyter notebook even when i have already successfully committed "pip install -U sentence-transformers" in powershell , to resolve this issue, use the same command "pip install -U sentence-transformers" in jupyter notebook and thn restart your kernel, it will surely work. : )

**Comment by GwNTM** [comment]
Hello,
I've successfully used sentence-transformers on my local conda environment but I am trying to use AzureML to optimize computing time, however I can't seem to use the package at all. It's very strange as it mentions it already being installed but I can't seem to find a way to use it in my notebook. Is there a special procedure that I should do and that I'm not aware of ? (see image)

![image](https://user-images.githubusercontent.com/19170649/155959864-b75beefb-d032-4060-a4a7-2c45766c0099.png)

Thanks a lot

**Comment by rowanhm** [comment]
same issue here. Pip seems to install fine, but the module won't import

**Comment by kashifmohammadML** [comment]
---------------------------------------------------------------------------
While importing keybet i am getting this error.

ModuleNotFoundError                       Traceback (most recent call last)
Input In [6], in <cell line: 1>()
----> 1 from keybert import keyBERT

File ~\anaconda3\envs\cq_data_dev_env\lib\site-packages\keybert\__init__.py:1, in <module>
----> 1 from keybert._model import KeyBERT
      3 __version__ = "0.6.0"

File ~\anaconda3\envs\cq_data_dev_env\lib\site-packages\keybert\_model.py:16, in <module>
     14 from keybert._maxsum import max_sum_distance
     15 from keybert._highlight import highlight_document
---> 16 from keybert.backend._utils import select_backend
     19 class KeyBERT:
     20     """
     21     A minimal method for keyword extraction with BERT
     22 
   (...)
     32     best describe the entire document.
     33     """

File ~\anaconda3\envs\cq_data_dev_env\lib\site-packages\keybert\backend\_utils.py:2, in <module>
      1 from ._base import BaseEmbedder
----> 2 from ._sentencetransformers import SentenceTransformerBackend
      3 from ._hftransformers import HFTransformerBackend
      4 from transformers.pipelines import Pipeline

File ~\anaconda3\envs\cq_data_dev_env\lib\site-packages\keybert\backend\_sentencetransformers.py:3, in <module>
      1 import numpy as np
      2 from typing import List, Union
----> 3 from sentence_transformers import SentenceTransformer
      5 from keybert.backend import BaseEmbedder
      8 class SentenceTransformerBackend(BaseEmbedder):

ModuleNotFoundError: No module named 'sentence_transformers'


and when importing sentence transformer

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Input In [8], in <cell line: 1>()
----> 1 from sentence_transformers import sentencetransformer

ModuleNotFoundError: No module named 'sentence_transformers'

**Comment by nreimers** [comment]
@kashifmohammadML Did you install it?

**Comment by kashifmohammadML** [comment]
@nreimers  yes, upon reinstalling it is showing "Requirement already satified"

**Comment by andrea-gatto** [comment]
I've got the same issue

**Comment by andrea-gatto** [comment]
fixed by upgrading python to 3.9.13 (sentence-transformers==2.2.2)

**Comment by ettabib101** [comment]
same problem here
![Capture d’écran 2022-08-17 090840](https://user-images.githubusercontent.com/104587144/185081678-9f54ed4a-708c-49be-a804-e9474e2c5f9d.png)

**Comment by zushi0516** [comment]
This might be helpful. It worked in my PC using this solution.
Before import sentence_transformers, add the path for your site-packages.


import sys
sys.path.append('[The path where the sentence_transformers reside on your PC]/Lib/site-packages')
from sentence_transformers import SentenceTransformer


For example, I use venv for my local, so the path is "~/.venv"

**Comment by thistleknot** [comment]
fixed by installing from source as outlined here:
https://pypi.org/project/sentence-transformers/

i.e. clone, cd into clone, pip install -e .

**Comment by fpawlows** [comment]
Use python 3.9.x (expecially 3.9.13) - its not working on 3.10.x for me

**Comment by Tomblib0** [comment]
Same problem of error after installing. But I worked it out: 
Pycharm -> file -> setting -> Project:xxx -> Python interpreter -> "+" -> search for "sentence_transformers" -> install -> Bingo!!!
It doesn't report any error !
Maybe we have to add it to project after installing packages.

**Comment by mahmud841** [comment]
> Same problem of error after installing. But I worked it out: Pycharm -> file -> setting -> Project:xxx -> Python interpreter -> "+" -> search for "sentence_transformers" -> install ->Bingo!!! It doesn't report any error ! Maybe we have to add it to project after installing packages.

it's work for me. Thanks a lot.

**Comment by AlJohri** [comment]
Is there a way to get this package working on Python 3.10?

I ran into this same error:

```
❯ python -c "from sentence_transformers import SentenceTransformer"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'sentence_transformers'
```

Downgrading to Python 3.9 fixed the issue.

**Comment by tomaarsen** [comment]
If you get `ModuleNotFoundError: No module named 'sentence_transformers'`, then `sentence_transformers` is not installed in that version/environment of Python. You can install it with `pip install sentence_transformers` or `python -m pip install sentence_transformers`.

**Comment by abhiram418** [comment]
It is for sure the **Python version problem** 
I uninstalled the python 12 --> installed python 14 and it is working now

**Comment by tomaarsen** [comment]
P.s. the `sentence_transformers.evaluation` module also moved to `sentence_transformers.sentence_transformer.evaluation`, but the old path still works albeit with a warning.

- Tom Aarsen
